console.log("test")
console.log ("seli, putri, amanda")
console.log ("bisa yu bisa")
console.log ("selamat pagi")
console.log ("hello")
console.log ("jangan lupa saranpan")
console.log("Selamat siang")
console.log("ganbatte")